### ISSUE TITLE
Thêm option "Tắt kiểm tra chính tả"

### ISSUE THREAD

**Issue by openhoangnc** [teni-ime/ibus-teni#17]
Hiện tại bộ gõ chỉ cho phép gõ chữ tiếng Việt có trong từ điển.
Nếu có option "Tắt kiểm tra chính tả" thì có thể gõ tự do hơn.

**Comment by wonbinbk** [comment]
Đồng ý.
Hoặc cho phép edit bộ "từ điển" của bộ gõ để người dùng thêm vào từ nào mình muốn.
Ví dụ, chữ "xịn" hiện nay không gõ được.

**Comment by openhoangnc** [comment]
Đã thêm option "Đúng chính tả" tại v1.4.0
