### ISSUE TITLE
Tạo danh sách loại trừ ứng dụng không dùng bộ gõ

### ISSUE THREAD

**Issue by openhoangnc** [teni-ime/ibus-teni#18]
Có một số ứng dụng không cần gõ tiếng Việt như VSCode,
nên có một danh sách loại trừ để không cần tắt bộ gõ khi chuyển ứng dụng.

**Comment by vimaxwell** [comment]
nếu có tính năng này thì hay, hiện tại mình dùng tính năng của ibus, mỗi ứng dụng mỗi kiểu gõ.

**Comment by openhoangnc** [comment]
Tham khảo
https://superuser.com/questions/382616/detecting-currently-active-window
https://unix.stackexchange.com/questions/38867/is-it-possible-to-retrieve-the-active-window-process-title-in-gnome
https://github.com/vbsw/xlib

**Comment by vimaxwell** [comment]
Mình thấy bản thân ibus có tích hợp tính năng này rồi. Mình có thể dùng tùy chọn thứ 2 là mỗi chương trình mình có thể dùng một ime khác nhau. Theo mình thấy nếu dùng các lệnh từ shell như đề xuất ở trên có thể không đảm bảo tốc độ.

Các bước tùy chỉnh:

![screenshot from 2018-08-26 22-03-59](https://user-images.githubusercontent.com/19898639/44629606-fd448d80-a97b-11e8-9261-ebcf70da2570.png)
chọn Option thứ 2:
![screenshot from 2018-08-05 18-51-10](https://user-images.githubusercontent.com/19898639/44629575-91fabb80-a97b-11e8-8d51-0a6df700d5f3.png)

**Comment by tm4dev** [comment]
@vimaxwell bro thấy nhưng đã dùng chưa? và dùng có thường xuyên không? 
mình thấy cái option của ibus khá tệ đó, nó nhớ input cho từng window rất kém, bật cái này lên có khi còn phải switch nhiều hơn là option 1 (use the same source for all).
Hơn nữa nếu có danh sách loại trừ thì quăng vào cái là xong, khỏi phải lăn tăn mỗi khi restart OS hoặc ibus :+1: ngon hơn cái option của ibus nhiều

**Comment by vimaxwell** [comment]
mình đang dùng đó @tm4dev. mình thấy api của ibus k hỗ trợ, nên hiện thực có thể làm performance chậm lại.

**Comment by vimaxwell** [comment]
Để chọn bộ gõ tiếng việt làm mặc định, bạn có thể chuyển bộ gõ **teni** lên trên bộ gõ English. Và ở cửa sổ (window) nào bạn k muốn gõ tiếng việt thì chuyển sang bộ gõ tiếng anh.
![screenshot from 2018-08-26 23-00-06](https://user-images.githubusercontent.com/19898639/44630191-ddb16300-a983-11e8-9b9c-54f82b3f3214.png)

**Comment by openhoangnc** [comment]
@vimaxwell @tm4dev cảm ơn ý kiến của các bạn
về performance bộ gõ thì mình nghĩ không có ảnh hưởng gì, mình sẽ dùng [lib x11 để lấy thông tin của window đang active](https://github.com/teni-ime/ibus-teni/blob/x11/src/x11/main.go), [bash shell](https://github.com/teni-ime/ibus-teni/blob/x11/src/x11/info.bash) dùng để đối chiếu trong lúc lập trình thôi.
