### ISSUE TITLE
Lỗi escape tiếng Việt

### ISSUE THREAD

**Issue by tuan-nng** [teni-ime/ibus-teni#26]
Mình muốn gõ "aws" thì gõ chuỗi kí tự awws sẽ không ra như ý muốn mà ra thành ws.

**Comment by openhoangnc** [comment]
@tuan-nng cảm ơn bạn đã tạo issue, bug này mình đã fix tại [v1.2.2](https://github.com/teni-ime/ibus-teni/releases/tag/v1.2.2)
Nếu đã cài đặt từ PPA hoặc OBS thì bạn có thể update ngay bây giờ (chạy `sudo apt upgrade` hoặc `sudo yum update`). Sau khi update cần chạy lại ibus bằng command `ibus restart`.
Nếu không còn vấn đề thì nhờ bạn close issue giúp mình.

**Comment by tuan-nng** [comment]
cảm ơn bạn đã phản hồi. Xác nhận là đã fix ở 1.2.2
