### ISSUE TITLE
Không gõ được tiếng việt trên Slack

### ISSUE THREAD

**Issue by rinleit** [teni-ime/ibus-teni#29]
Hi các bạn,

Vì đặc thù công việc mình hay dùng Slack, mỗi lúc vào slack thì lại không gõ được tiếng việt.
Mình không rõ là có option nào để kích hoạt không hay là lỗi.

Cám ơn các bạn!

**Comment by vimaxwell** [comment]
mình vẫn đang dùng trên slack bình thường. Bạn đang dùng bản slack chuẩn hay bản trên snap vậy? Theo mình biết, bản snap hiện tại k tương thích với ibus tốt.

**Comment by rinleit** [comment]
Cám ơn bạn. Mình đang dùng bản Snap. Để mình tải bản chuẩn xem sao :D
