### ISSUE TITLE
Hỗ trợ gõ nhanh ở kiểu gõ telex

### ISSUE THREAD

**Issue by vimaxwell** [teni-ime/ibus-teni#3]
+ Gõ 'w' thay cho 'ư'
+ gõ '[' thay cho 'ơ'

**Comment by openhoangnc** [comment]
Từ khi xây dựng bộ gõ mình đã có ý định không hỗ trợ kiểu gõ này vì mình thấy
* cần gõ chữ w nhiều hơn là gõ nhanh chữ ư
* gõ cặp dấu "[", "]" nhiều hơn là gõ nhanh chữ ơ

Tuy nhiên cũng có nhiều người quen gõ nhanh như đề xuất của bạn.
Mình sẽ thêm kiểu gõ Telex và hỗ trợ gõ nhanh trong milestone sau.

**Comment by danglduy** [comment]
@openhoangnc Định tạo issue mới nhưng thấy reply của bạn nên mình cũng rất chờ bạn ra bộ gõ telex.

**Comment by openhoangnc** [comment]
Mình đã thêm kiểu gõ telex tại [branch telex](https://github.com/teni-ime/ibus-teni/tree/telex)
Nhờ các bạn bỏ chút thời gian test giúp, khi ổn định mình sẽ merge và release
