### ISSUE TITLE
Không thể dùng 'Show Keyboard Layout'

### ISSUE THREAD

**Issue by vimaxwell** [teni-ime/ibus-teni#4]
Tính năng này không hoạt động ở ubuntu 18.04

**Comment by openhoangnc** [comment]
@vimaxwell cảm ơn bạn đã báo lỗi, mình sẽ close issue này với label wontfix, tuy nhiên bất cứ khi nào bạn cũng có thể thêm comment và nếu cần thì có thể open lại.
