### ISSUE TITLE
Chữ không hiện ra ở chức năng gõ tiếng Việt telex trên Ubuntu

### ISSUE THREAD

**Issue by manaclan** [teni-ime/ibus-teni#41]
Gõ một vài ký tự rồi xóa các ký tự vừa gõ , click con trỏ chuột sang vị trí khác để gõ thì chữ không hiện ra.

**Comment by openhoangnc** [comment]
@manaclan mình không tái hiện được tình trạng như bạn mô tả, bạn có thể cung cấp chi tiết hơn không?
Như là phiên bản Ubuntu nào, có sử dụng Desktop Enviroment khác không, chương trình bạn muốn gõ tiếng Việt là gì?

Ảnh chụp màn hình hoặc tốt nhất là quay lại màn hình sẽ giúp mình dễ phán đoán hơn.
Quay phim màn hình bạn có thể tham khảo hướng dẫn tại https://www.youtube.com/watch?v=N8M4zsqTkr4

**Comment by manaclan** [comment]
Chào anh, em dùng phiên bản ubuntu 18.04.
Em mở máy lên với teni đang bật test trên git hub wiki (trình duyệt fire fox) thì không sao nhưng sau khi chuyển qua gõ tiếng Anh rồi chuyển lại tiếng Việt thì lỗi xuất hiện. Em đã quay lỗi lại, anh vào xem ở link này: https://youtu.be/plcIQ8xCvLk

**Comment by openhoangnc** [comment]
@manaclan mình đã fix lỗi này tại v1.3.3, nhờ bạn test lại giúp mình

**Comment by manaclan** [comment]
Lỗi này sửa được rồi mà nó bị lỗi mới rồi anh @@. Để em tạo issue mới

**Comment by manaclan** [comment]
Gõ một hồi lỗi này lại xuất hiện anh à. Lần này bao gồm lỗi cũ lẫn mới. Video: https://youtu.be/FgXTKFt69q8
