### ISSUE TITLE
Chữ không hiện sau khi bôi đen

### ISSUE THREAD

**Issue by manaclan** [teni-ime/ibus-teni#43]
OS: Ubuntu 18.04
Teni: 1.3.3
Môi trường: firefox
Gõ chữ rồi bôi đen thì không ghi đè chữ mới lên. Video tham khảo: https://www.youtube.com/watch?v=wd8GdqndRg4&list=PLcLo79gUxLkZU1z1uijjETuo0A99tzfCh

**Comment by openhoangnc** [comment]
@manaclan mình đã kiểm tra vấn đề này, chi tiết như sau:
Ở trạng thái đang gõ (chữ còn dấu gạch chân) và click chuột trong cùng một textbox thì không có event đổi focus, bộ nhớ đệm vẫn đang trạng thái xử lý từ đang gõ, do đó nếu tiếp tục gõ sau khi click thì sẽ phát sinh vấn đề như trên.
Cách xử lý thì mình đã có ghi trong hướng dẫn sử dụng tại wiki:
- Nhấn phím Ctrl để kết thúc chữ đang gõ trước khi click chuột đi chỗ khác
- Hoặc cấp quyền đọc event chuột bằng command ```sudo chmod +r /dev/input/mice``` (cần chạy lại ibus bằng ```ibus restart```) thì ibus-teni sẽ kiểm tra được khi nào có event click chuột để kết thúc xử lý chữ đang gõ

**Comment by vimaxwell** [comment]
@openhoangnc bên ibus cũng đang fix, bạn test bản fix của bên họ có giải quyết được k
https://github.com/ibus/ibus/issues/1980

**Comment by manaclan** [comment]
@openhoangnc thanks anh đã giải quyết được.

**Comment by openhoangnc** [comment]
@vimaxwell về việc bên ibus đang fix bug này, mình đã tạo issue #45
