### ISSUE TITLE
Subline Text

### ISSUE THREAD

**Issue by thanhcong2930** [teni-ime/ibus-teni#44]
Không gõ tiếng việt trên subline text được.
test trên ibus unikey cũng y vậy, hi vọng ad fix dc .
Cám ơn ạ.

**Comment by khanhicetea** [comment]
Tình trạng này cũng xảy ra ở các Apps viết bằng Qt (đặc biệt là Qt5).

**Comment by openhoangnc** [comment]
@thanhcong2930 @khanhicetea 
Đây là vấn đề chung của các app trên snapcraft store, mặc dù snap có hỗ trợ ibus nhưng hầu hết các package khi đóng gói không kèm các package hỗ trợ cho ibus.
Giải pháp hiện tại là cài và sử dùng trực tiếp các app đó từ website chính thức:
- http://www.sublimetext.com/docs/3/linux_repositories.html

**Comment by khanhicetea** [comment]
Yah, mình cũng nghĩ vậy vì trong desktop-launch script của Telegram (cài qua Snap) cũng có đoạn check xem nếu `QT_IM_MODULE=ibus` thì nó cũng set lại bằng `xim`

Mình tải bản Telegram trên web chính thức về `export QT_IM_MODULE=ibus` chạy thì gõ bình thường trên Ubuntu 18.04 (còn 16.04 thì không cần vẫn gõ được qua ibus-teni).

Cảm ơn bạn đã xây dựng thư viện này ! 👍

**Comment by openhoangnc** [comment]
mình close issue này, vấn đề ngoài khả năng giải quyết quả bộ gõ này
