### ISSUE TITLE
Teni tạo nhiều connection lên display, gây nghẽn

### ISSUE THREAD

**Issue by wonbinbk** [teni-ime/ibus-teni#46]
Hi, mình mô tả trường hợp của mình như sau:
- OS: Manjaro KDE.
- Máy chạy một thời gian sẽ có hiện tượng không thể mở thêm bất kỳ ứng dụng nào. Lỗi trả về là:

> Maximum number of clients reachedUnable to init server: Could not connect: Connection refused
Error: cannot open display: :0

Mình dùng lệnh lsof để coi các connection:

> lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3
>    212 ibus-engine-ten
>    119 chrome
>     99 dbus-daemon

Ibus teni luôn tạo rất nhiều connection (mà chắc là không đóng) nên càng chạy teni thì số lượng càng tăng dẫn đến nghẽn luôn.
Liệu đây có phải issue của teni hay của Manjaro? Mình không rành lắm nên không chắc.

Sau khi kill ibus teni đi thì có thể mở được các ứng dụng bình thường.

Thanks.

**Comment by openhoangnc** [comment]
@wonbinbk 
mình hơi ngạc nhiên vì mô tả của bạn, nhờ bạn list chi tiết giúp mình
```sudo lsof -p <process id của ibus-teni>```

**Comment by wonbinbk** [comment]
Hi bạn,
Mình đã tháo ibus teni và chỉ dùng ibus unikey thì vấn đề vẫn còn nên có lẽ không phải do teni.
Bạn có thể close issue này rồi.

**Comment by openhoangnc** [comment]
@wonbinbk 
Mình close issue này tại đây.
Nếu có thêm thông tin liên quan đến vấn đề này thì bạn có thể re-open bất cứ lúc nào.

**Comment by vimaxwell** [comment]
@wonbinbk nếu dc thì bạn hãy report vào repo của ibus để họ fix luôn. https://github.com/ibus/ibus

**Comment by wonbinbk** [comment]
> @wonbinbk
> mình hơi ngạc nhiên vì mô tả của bạn, nhờ bạn list chi tiết giúp mình
> `sudo lsof -p <process id của ibus-teni>`

Mình không biết là có giúp gì được không, nhưng mình đã cài lại ibus-teni và dùng lại xem sao, hiện tại chưa gặp trường hợp như trước.
Nhưng đây là output của lệnh bạn yêu cầu:

```
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse file system /run/user/1000/doc
      Output information may be incomplete.
COMMAND    PID USER   FD      TYPE             DEVICE SIZE/OFF   NODE NAME
ibus-engi 1182 thai  cwd       DIR                8,2     4096 486457 /usr/share/ibus-teni
ibus-engi 1182 thai  rtd       DIR                8,2     4096      2 /
ibus-engi 1182 thai  txt       REG                8,2  2387472 394243 /usr/lib/ibus-engine-teni
ibus-engi 1182 thai  mem       REG                8,2    55192 405572 /usr/lib/libnss_files-2.28.so
ibus-engi 1182 thai  mem       REG                8,2 51253280 397546 /usr/lib/libgo.so.13.0.0
ibus-engi 1182 thai  mem       REG                8,2  2136840 401792 /usr/lib/libc-2.28.so
ibus-engi 1182 thai  mem       REG                8,2   155408 420486 /usr/lib/libpthread-2.28.so
ibus-engi 1182 thai  mem       REG                8,2   165624 404106 /usr/lib/libxcb.so.1.1.0
ibus-engi 1182 thai  mem       REG                8,2   193680 401781 /usr/lib/ld-2.28.so
ibus-engi 1182 thai  mem       REG                8,2    22120 399013 /usr/lib/libXdmcp.so.6.0.0
ibus-engi 1182 thai  mem       REG                8,2    15224 399011 /usr/lib/libXau.so.6.0.0
ibus-engi 1182 thai  mem       REG                8,2    14232 401801 /usr/lib/libdl-2.28.so
ibus-engi 1182 thai  mem       REG                8,2    91912 404121 /usr/lib/libz.so.1.2.11
ibus-engi 1182 thai  mem       REG                8,2   867312 397435 /usr/lib/libgcc_s.so.1
ibus-engi 1182 thai  mem       REG                8,2  1587096 401807 /usr/lib/libm-2.28.so
ibus-engi 1182 thai  mem       REG                8,2  1300568 425606 /usr/lib/libX11.so.6.3.0
ibus-engi 1182 thai    0r      CHR                1,3      0t0      5 /dev/null
ibus-engi 1182 thai    1w      CHR                1,3      0t0      5 /dev/null
ibus-engi 1182 thai    2w      CHR                1,3      0t0      5 /dev/null
ibus-engi 1182 thai    3u     unix 0x00000000198d9807      0t0  23252 type=STREAM
ibus-engi 1182 thai    4u  a_inode               0,13        0  10750 [eventpoll]
```
