### ISSUE TITLE
Hướng dẫn compile?

### ISSUE THREAD

**Issue by minhducsun2002** [teni-ime/ibus-teni#50]
Không có hướng dẫn build lại từ mã nguồn.
Nhiều người không biết cách build package cho Debian.

**Comment by openhoangnc** [comment]
bạn vui lòng đọc lại readme

**Comment by minhducsun2002** [comment]
Mình xin lỗi vì không đọc kỹ, rất cảm ơn bạn.

--- 

Sorry for not reading carefully, thank you very much.
