### ISSUE TITLE
Có hiện tượng giật lag khi gõ trên terminal của PyCharm

### ISSUE THREAD

**Issue by ChuPhong** [teni-ime/ibus-teni#51]
**Mô tả lỗi**
Khi em bật terminal trên PyCharm và gõ thì xảy ra hiện tượng giật lag, các chữ nhập vào không hiển thị ngay lập tức mà bị giật giật, khoảng 0.5s sau mới hiện chữ lên. Em thử chuyển qua bộ gõ tiếng Anh thì hiện tượng trên không còn.

**Các bước tái hiện lỗi**
- Mở PyCharm
- Chuyển sang tab terminal
- Gõ chữ

**Kết quả mong muốn**
Em muốn gõ chữ phải hiện ngay lập tức, chứ không phải bị delay :(

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://www.youtube.com/watch?v=jXK7krTl6a8

0s - 8s: Sử dụng bộ gõ ibus-teni
9s -> hết: Chuyển về lại bộ gõ tiếng Anh

**Môi trường**
 - OS và version: 18.04.1
 - Desktop: Mặc định
 - Phiên bản ibus-teni: v1.4.0

**Thông tin thêm**
 - PyCharm: 2018.2

**Comment by openhoangnc** [comment]
cảm ơn báo lỗi của bạn, mình sẽ kiểm tra và tìm cách khắc phục
