### ISSUE TITLE
Lỗi chữ "Lố" trên visual studio code

### ISSUE THREAD

**Issue by ChuPhong** [teni-ime/ibus-teni#53]
**Mô tả lỗi**
Thay vì hiện chữ "Lố" thì nó lại hiện lệch dấu sắc sang 1 bên
Em có thử test trên Chrome và một số app khác thì vẫn oke.

**Các bước tái hiện lỗi**
- Mở visual studio code
- Gõ chữ "Lố"

**Kết quả mong muốn**
Hiện chữ "Lố" thay vì như trên

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![selection_003](https://user-images.githubusercontent.com/36165008/47002912-577df580-d158-11e8-9405-047f65a45bf8.png)

**Môi trường**
 - Ubuntu 18.04
 - Phiên bản ibus-teni: (v1.4.0)

**Thông tin thêm**
 - Visual studio code: 1.28.1

**Comment by Meigyoku-Thmn** [comment]
Do font chữ được dùng trong VSCode không support Tiếng Việt thôi, đổi sang font khác là ok.

**Comment by openhoangnc** [comment]
@ChuPhong bạn thử đổi font khác rồi báo kết quả giúp mình nhé.

**Comment by linhusp** [comment]
@ChuPhong Font menlo gõ tiếng việt trên vscode là sẽ bị như vậy. Thay vì xài menlo bạn có thể thử meslo font, sẽ không bị lỗi font nữa.

**Comment by openhoangnc** [comment]
@ChuPhong Mình close issue này vì thấy là lỗi do font chữ, nếu bạn đã đổi font mà vẫn còn lỗi thì bạn có thể cung cấp thêm thông tin chi tiết và mở lại issue này.
