### ISSUE TITLE
Lỗi khi xóa các ký tự trên Telegram Desktop

### ISSUE THREAD

**Issue by nploi** [teni-ime/ibus-teni#55]
**Mô tả lỗi**
- Khi xóa các chữ thì không xóa ký tự cuối.
- Khi còn một ký tự thì không xóa được, phải bấm nhiều lần rồi gõ lại thì mất ký tự đó.

**Các bước tái hiện lỗi**
1. Mở Telegram Desktop
2. Gõ nhiều chữ bất kỳ
4. Bấm Backspace để xóa các ký tự 
5. Sẽ thấy những lỗi mô tả ở trên

**Kết quả mong muốn**
- Khi gõ các chữ thì xóa được các ký tự, và ký tự đầu tiên

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![bug](https://user-images.githubusercontent.com/34020090/47228425-629e8300-d3ef-11e8-838d-eeb240f5493f.gif)

**Môi trường**
 - OS và version: Ubuntu 18.10
 - Desktop: Gnome
 - Phiên bản ibus-teni: (v1.4.0)

**Thông tin thêm**
- [Telegram Desktop](https://desktop.telegram.org/)

**Comment by openhoangnc** [comment]
@nploi mình mới release v1.4.1, nhờ bạn test lại xem còn lỗi không

**Comment by nvt1904** [comment]
mình bị lỗi không gõ được tiếng việt trên telegram là sao bạn ?

**Comment by openhoangnc** [comment]
@nvt1904 bạn cần tải Telegam Desktop trực tiếp từ web và chạy, nếu vẫn không gõ được thì thử thêm mấy dòng cấu hình Input Method sau vào file .profile bằng cách chạy các command bên dưới rồi restart lại máy.

```
echo CLUTTER_IM_MODULE=ibus >>~/.profile
echo QT4_IM_MODULE=ibus >>~/.profile
echo QT_IM_MODULE=ibus >>~/.profile
echo GTK_IM_MODULE=ibus >>~/.profile
```
