### ISSUE TITLE
đăng kí bộ gõ lên các repo

### ISSUE THREAD

**Issue by vimaxwell** [teni-ime/ibus-teni#6]
Mình có 3 đề xuất thế này:
1. hiện tại cách cài đặt vẫn là tải gói về rồi sau đó cài đặt, như vậy hơi bất tiện trong việc thông báo các phiên bản mới của bộ gõ. Mình đề xuất upload lên các repo khác như ibus-unikey https://pkgs.org/download/ibus-unikey
2. Viết document cho việc build bằng source code.
3. Tạo trang hướng dẫn cho người dùng ở một trang riêng biệt thay cho wiki vì wiki hướng tới dev nhiều hơn. (vd: http://square.github.io/retrofit/)

**Comment by openhoangnc** [comment]
Đề xuất 1 và 2 của bạn đã có tại wiki [Hướng dẫn cài đặt](https://github.com/teni-ime/ibus-teni/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t).

Trang hướng dẫn cho người dùng thì tạm thời mình thấy chưa cần, người dùng Linux hầu hết là người am hiểu kĩ thuật nên có thể tự tìm hiểu được.

**Comment by openhoangnc** [comment]
Mình đã tạo package PPA và đã cập nhật [hướng dẫn cài đặt](https://github.com/teni-ime/ibus-teni/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t/_edit#c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-ppa-cho-ubuntu).

Còn trang hướng dẫn mình sẽ thực hiện sau.
Bây giờ mình sẽ close issue này.
Cảm ơn các đề xuất của bạn.
