### ISSUE TITLE
Gõ dấu khi kết thúc từ 

### ISSUE THREAD

**Issue by giangm9** [teni-ime/ibus-teni#66]
**Mô tả lỗi**
Gõ meeuf thì sẽ ra mêuf 
gỗ meefu thì ra mều

**Các bước tái hiện lỗi**
Chọn setting như trong này 
![screenshot from 2018-11-21 20-45-39](https://user-images.githubusercontent.com/10234339/48845235-8ed26880-edce-11e8-9c11-84b2a7a3c32d.png)
Sau đó gõ như mô tả 
4. Thấy xyz
Như trong mô tả 

**Kết quả mong muốn**
Gõ meeuf ra mều
**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: Ubuntu 16.04
 - Desktop: i3
 - Phiên bản ibus-teni: 1.5.9
 - Phiên bản IBus: 1.5.11
 - Ứng dụng có lỗi khi gõ: any

**Comment by openhoangnc** [comment]
@giangm9 @manhnt9 nguyên nhân là từ "mều" là tiếng lóng, không có trong từ điển, bản release tiếp theo khắc phục được.

**Comment by openhoangnc** [comment]
@giangm9 v1.5.1 đã giải quyết được vấn đề này, mình close issue này. Nếu bạn thấy vẫn chưa khắc phục được thì bạn có thể re-open issue này hoặc tạo issue khác nếu gặp vấn đề gì khác.

**Comment by giangm9** [comment]
Đã cập nhật và gõ được đúng như mong muốn :D
