### ISSUE TITLE
Lỗi gõ từ In hoa

### ISSUE THREAD

**Issue by thanhcong2930** [teni-ime/ibus-teni#68]
Một từ in hoa không gõ được tiếng việt như là DD Dd k ra Đ, e có reinstall rồi nhưng vẫn bị z.

**Comment by openhoangnc** [comment]
@thanhcong2930 mình sẽ sớm sửa lỗi, trước mắt bạn có thể bật "Đúng chính tả" thì sẽ gõ được

**Comment by thanhcong2930** [comment]
Cám ơn ad. :D

**Comment by openhoangnc** [comment]
@thanhcong2930 mình đã fix tại v1.5.2
