### ISSUE TITLE
Mất chữ khi gõ trên browser

### ISSUE THREAD

**Issue by vanhonit** [teni-ime/ibus-teni#7]
Khi gõ địa chỉ website trên trình duyệt trình duyệt có tính năng tự động điền. Ví dụ khi mình gõ fa thì trình duyệt sẽ điền đầy đủ là facebook.com, người dùng chỉ cần gõ enter là vào website nhưng khi bật Teni khi gõ fa rồi enter sẽ bị hiểu nhầm là search "fa". Ibus-unikey k bị lỗi này.
![screenshot from 2018-08-10 17-39-47](https://user-images.githubusercontent.com/1215676/43953815-74011cd2-9cc4-11e8-897f-cc371323a063.png)

**Comment by openhoangnc** [comment]
@vanhonit cảm ơn bạn đã tạo issue.
Để trình duyệt tự động điền thì bạn cần "_commit_" trước khi nhấn enter, bằng cách **nhấn phím Ctrl** hoặc các phím mũi tên, cũng có thể dùng **phím Esc** nếu chữ bạn gõ không có dấu.

**Comment by openhoangnc** [comment]
Mình đã fix lỗi này, hiện tại bạn có thể [cài đặt từ mã nguồn](https://github.com/teni-ime/ibus-teni/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t#t%E1%BA%A3i-m%C3%A3-ngu%E1%BB%93n-build-v%C3%A0-install) để test, mình sẽ sớm release chính thức.
