### ISSUE TITLE
Khi bỏ "đúng chính tả" thì không gõ được chữ "đ" viết hoa.

### ISSUE THREAD

**Issue by wonbinbk** [teni-ime/ibus-teni#70]
**Mô tả lỗi**
Không gõ được chữ đờ hoa trên Chrome

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
0. Thiết lập teni bỏ chọn "đúng chính tả".
1. Mở chrome.
2. Sử dụng facebook và bình luận hoặc bất kỳ chỗ nào nhập text được trong web, kể cả cái github này.
3. Gõ chữ, ví dụ "đúng" với chữ đ viết hoa.
4. Nó ra chữ "Dungds" hoặc "DDúng" chứ không phải "đúng" với đ viết hoa.

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Ra chữ đ viết hoa.

**Môi trường**
 - OS và version: Debian 9.6
 - Desktop: KDE
 - Phiên bản ibus-teni: 1.5.1
 - Phiên bản IBus: 1.5.14
 - Ứng dụng có lỗi khi gõ: Chrome, Kate, bất kỳ.

**Comment by openhoangnc** [comment]
@wonbinbk mình đã fix lỗi này ở v1.5.2 và đã release, bạn có thể cập nhật và thử lại giúp mình được không

**Comment by wonbinbk** [comment]
A, cám ơn bạn Đã fix với tốc độ ánh sáng.
Mình Đã làm Được rồi Đây.
