### ISSUE TITLE
Không sử dụng được ibus-teni trên Telegram (Ubuntu 16.04)

### ISSUE THREAD

**Issue by huyndnse63331** [teni-ime/ibus-teni#73]
Bạn kiểm tra lại giùm mình vì mình không thể gõ tiếng Việt trên Telegram được mặc dù mình vẫn có thể gõ tiếng Việt ở những ứng dụng khác. Mình đang sử dụng Ubuntu 16.04.5 (amd64)

**Comment by manhnt9** [comment]
Mình dùng Ubuntu 18.04 và Telegram 1.4.3 gõ được bình thường.

**Comment by khanhicetea** [comment]
Bạn download binary từ trang chủ về tự cài file Desktop để làm App nhé

Cài đặt qua snap sẽ bị bug giữa snap và ibus nên bug này nằm ngoài phạm vi của repo

**Comment by huyndnse63331** [comment]
à mình cài Telegram thông qua snap, để mình cài lại với binary

**Comment by khanhicetea** [comment]
Đây là file desktop của mình nếu bạn muốn dùng cho nhanh, bạn change lại Telegram path nhé

~/.local/share/applications/telegramdesktop.desktop

```
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop application for the Telegram messaging service
TryExec=/home/khanhicetea/tool/telegram/Telegram
Exec=/home/khanhicetea/tool/telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
X-Desktop-File-Install-Version=0.22
```

Nếu đã ok thì bạn close issues nhé :smile:

**Comment by huyndnse63331** [comment]
Mình tạo được file desktop shortcut nha và mình cũng đã gõ được tiếng Việt trên Telegram, cảm ơn @khanhicetea nhé <3 Mình xin phép close đây

**Comment by khanhicetea** [comment]
@huyndnse63331  :+1: 

@openhoangnc mình thấy nhiều bạn report vấn đề không gõ được với các snap apps , nên mình nghĩ nên thêm một lưu ý những lỗi thường gặp ở README để mọi người có thể hiểu và không report issues trùng và tốn nhiều thời gian giải đáp lặp lại.

**Comment by zoom360** [comment]
> @huyndnse63331  
> 
> @openhoangnc mình thấy nhiều bạn report vấn đề không gõ được với các snap apps , nên mình nghĩ nên thêm một lưu ý những lỗi thường gặp ở README để mọi người có thể hiểu và không report issues trùng và tốn nhiều thời gian giải đáp lặp lại.

Mình cũng gặp phải vấn đề này, Telegram mình tải file ded về tạo file desktop nhưng không gõ được.

**Comment by wforfun** [comment]
bạn thử cách chạy telegram bằng bằng terminal xem sao 
```
QT_IM_MODULE=ibus telegram-desktop &
```

**Comment by zoom360** [comment]
> bác thử cách chạy telegram bằng bằng terminal xem sao
> 
> ```
> QT_IM_MODULE=ibus telegram-desktop &
> ```
> nhớ chạy ibus trước khi chạy telegram,
> 
> nếu chạy bằng lệnh ok thì bác sửa file desktop như sau:
> 
> ```
> [Desktop Entry]
> Version=1.0
> Name=Telegram Desktop
> Comment=Official desktop application for the Telegram messaging service
> TryExec=/usr/bin/telegram-desktop
> Exec=env QT_IM_MODULE=ibus /usr/bin/telegram-desktop -- %u
> Icon=telegram
> Terminal=false
> StartupWMClass=TelegramDesktop
> Type=Application
> Categories=Network;InstantMessaging;Qt;
> MimeType=x-scheme-handler/tg;
> Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
> X-GNOME-UsesNotifications=true
> X-Desktop-File-Install-Version=0.24
> ```

Thanks bạn! Mình đã fix được rồi nhưng không phải cách trên. Mình cài Telegram bằng lệnh sudo apt install telegram-desktop tự nhiên gõ được luôn.
