### ISSUE TITLE
Lỗi không nhận pre-edit trên chromium

### ISSUE THREAD

**Issue by quanghainguyen1512** [teni-ime/ibus-teni#74]
**Mô tả lỗi**
Teni không hoạt động trên Chromium

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở Chromium (Version 70.0.3538.110 (Official Build) snap (64-bit))
2. Gõ tiếng Việt (telex và vni).
3. Không hoạt động

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://www.youtube.com/watch?v=j51TdTl_5kQ

**Môi trường**
 - OS: Ubuntu - VERSION="18.04.1 LTS (Bionic Beaver)"
 - Desktop: Gnome
 - Phiên bản ibus-teni: v1.5.2
 - Phiên bản IBus: v1.5.17
 - Ứng dụng có lỗi khi gõ: Chromium

**Comment by khanhicetea** [comment]
ibus không chạy trên các snap apps nhé bạn , bạn down chromium từ `apt` hoặc file `deb` nhé. Nếu chạy được thì bạn close issues nhé.

**Comment by quanghainguyen1512** [comment]
Vâng cảm ơn bạn, mình đã cài bằng apt và chạy được, tại trước đây mình dùng vẫn ok nhưng khi cập nhật bản mới thì bị lỗi ấy
