### ISSUE TITLE
Mất từ khi gõ chữ

### ISSUE THREAD

**Issue by thanhcong2930** [teni-ime/ibus-teni#75]
Tình hình là khi e gõ chữ, cứ di chuyển con trỏ chuột là mất chữ. Này có phải lỗi của ibus-teni hay không ạ. Cám ơn 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43547296/49686277-cfe3b000-fb24-11e8-9ac2-ac762479a4cb.gif)

**Comment by openhoangnc** [comment]
vấn đề này mình đã giải thích ở hướng dẫn sử dụng, https://github.com/teni-ime/ibus-teni/blob/master/README.md
