### ISSUE TITLE
Hỗ trợ gõ ở app chạy trên Wine

### ISSUE THREAD

**Issue by vimaxwell** [teni-ime/ibus-teni#8]
Mình thấy bộ gõ không hoạt với phần mềm Notepad++ trên Wine, còn trên ibus-unikey thì hoạt động.

**Comment by openhoangnc** [comment]
@vimaxwell cảm ơn bạn đã tạo issue, mình sẽ kiểm tra và tìm cách khắc phục

**Comment by openhoangnc** [comment]
@vimaxwell mình mới kiểm tra trên bản 1.2.0 (release sau khi bạn tạo issue 2 ngày) và thấy gõ trên Nodepad++ chạy trên wine.

Nhờ bạn cài đặt bản 1.2.0 và kiểm tra lại một lần nữa giúp mình.

**Comment by vimaxwell** [comment]
mình mới thử lại vẫn chạy k nữa, để mình thử những phần mềm khác xem sao.

**Comment by thuvh** [comment]
cho mình hỏi cái này sẽ là problem của teni hay của ibus nhỉ? mình vừa search thấy cũng có một vài issue liên quan đến ibus + wine [link](https://github.com/ibus/ibus/search?q=wine&type=Issues)

**Comment by openhoangnc** [comment]
@thuvh cảm ơn thông tin của bạn, hiện tại người dùng wine có giải pháp là cài trực tiếp unikey trong wine
Mình có kiểm tra thử thì thấy trên openSUSE vẫn gõ được, trên Ubuntu thì không gõ được.

**Comment by vimaxwell** [comment]
@openhoangnc mình đã gõ được ở notepad++ trên wine

**Comment by openhoangnc** [comment]
@vimaxwell notepad++ trên Ubuntu store là đóng gói Wine trong Snap, khả năng tương thích bộ gõ liên quan tới cả IBus, Snap và Wine.
Trước mắt là đã hoàn thành hỗ trợ gõ app chạy trên Wine nên mình sẽ close issue này.
