### ISSUE TITLE
Đề xuất kết hợp dự án Bamboo và Teni

### ISSUE THREAD

**Issue by manhnt9** [teni-ime/ibus-teni#81]
Mình thấy rất vui khi cộng đồng Linux nói chung và Linux ở Việt Nam có những dự án như Teni. Mấy năm trước đây vấn đề bộ gõ gây ra nhiều phiền khi sử dụng Linux. Hiện tại chúng ta có thêm nhiều lựa chọn hơn. Tuy nhiên để tránh sự phân mảnh, chúng ta nên tìm cách kết hợp các dự án lại với nhau để tạo nên một phần mềm thực sự tốt và bền vững. 

Dự án [Bamboo](https://github.com/BambooEngine/ibus-bamboo) là một bộ gõ tiếng Việt mới, rất tương đồng với Teni và cũng được lập trình bằng ngôn ngữ Go. Đọc kỹ thì thấy nó được fork từ Teni.
Mình đề xuất rằng chúng ta cùng có các động thái khuyến khích nhà phát triển kết hợp:
- Port các tính năng từ Bamboo qua Teni, hợp nhất thành một dự án Teni
- Kết hợp cả hai dự án thành một dự án mới

Mời mọi người cho ý kiến thảo luận.
Nguyễn Tiến Mạnh.

**Comment by openhoangnc** [comment]
@manhnt9 cảm ơn đề xuất của bạn
Một số nhận định và ý kiến của mình:
- Tác giả project bamboo có không có định hướng kết hợp, toàn bộ project được re-upload mà không fork từ github, sau khi mình có ý kiến mới cập nhật nguồn fork
- Mình không phát triển nhiều tính năng mà người dùng không sử dụng như: các bảng mã và kiểu gõ cũ
- Vì đã mở mã nguồn nên mọi người đều có thể phát triển miễn là tuân thủ giấy phép mã nguồn mở
- Quan sát một số dự án trước thì mình thấy gom nhiều nhà phát triển lại sẽ khiến dự án chết nhanh hơn

Nếu người dùng cần một tính năng nào đó thì có một số lựa chọn:
- Yêu cầu phát triển tính năng mới
- Yêu cầu port tính năng từ project khác
- Tự phát triển và đóng góp vào project này
- Tự phát triển và mở ra project mới

**Comment by luongthanhlam** [comment]
@manhnt9 hai bộ gõ sử dụng 2 engine khác nhau, đối tượng người dùng cũng khác nhau, nếu gộp sẽ buộc phải lựa chọn một trong hai
@openhoangnc nguồn fork của ibus-bamboo mình đã ghi rất rõ trong wiki và file AUTHORS, không rõ vì lí do gì mà bạn nhất quyết muốn ghi trong README?

**Comment by openhoangnc** [comment]
@luongthanhlam tại dự án này, mình rõ mọi nguồn tham chiếu, tham khảo tại README **để mọi người đều biết**, mình tôn trọng mọi công sức của những người đã thực hiện các dự án trước và mình mong muốn bạn cũng như vậy.

**Comment by luongthanhlam** [comment]
Với mình thì README hay AUTHORS đều có giá trị như nhau, không có chuyện vì github mặc định README mà AUTHORS vô giá trị. Tuy nhiên mình tôn trọng ý kiến của bạn.

**Comment by manhnt9** [comment]
Sau khi sử dụng thử 2 bộ gõ thì mình có ý kiến như sau:
- Core của Teni rất tốt, cài đặt là dùng được luôn nhiều phần mềm, Bamboo hiện đang bị một [lỗi](https://github.com/BambooEngine/ibus-bamboo/issues/17) khá là khó sử dụng nên mình đang dùng tiếp Teni. Dù sao basic feature phải thật ổn thì mới tính đến việc nâng cấp, tác giả Teni đã làm tốt điều này.
- Bamboo có khả hướng tới đông đảo người dùng hơn với những tiện ích như không có gạch chân, gõ emoji, ... mình thấy rất hứng thú. Tuy nhiên hiện vẫn còn có lỗi và có thêm các tính năng khá phức tạp, 4 mode bỏ gạch chân, nhiều bảng mã và kiểu gõ, nhìn chung là có nhiều option sẽ khiến code base khó ổn định.
- Mình vẫn rất mong muốn hai tác giả có thể cùng kết hợp để tạo ra một bộ gõ thật tốt cho tất cả mọi người cùng sử dụng. Nếu hai bên chịu hợp tác cởi mở, mình sẵn sàng nhận trách nhiệm trung hòa các định hướng phát triển nếu hai bạn đồng ý.
- Gợi ý dành cho tác giả Teni: tính năng emoji có thể chưa cấp thiết lắm, tuy nhiên bỏ gạch chân là một thay đổi rất đáng kể về trải nghiệm người dùng. Hi vọng bạn cân nhắc phát triển.

**Comment by manhnt9** [comment]
Tuy là mất thời gian nhưng mình thấy lợi ích về lâu dài sẽ tốt.
Cả 2 tác giả độc lập rồi cũng sẽ không tiếp tục được mãi. Kết hợp lại để có sự cởi mở, về sau ai cũng có thể join vào cái chung đó tiếp tục phát triển. Lâu nay các bộ gõ khác vẫn tiếp tục mọc lên: bogo, teni, bamboo, ...
Nếu chúng ta không sớm kết hợp, về sau sẽ còn phân mảnh nữa và người dùng luôn phải chờ đợi những bộ gõ tốt hơn.

**Comment by luongthanhlam** [comment]
Mình nghĩ việc một bộ gõ có phát triển được lâu dài hay không không nằm ở việc có một hay nhiều người duy trì phát triển mà nằm ở tính năng nó mang lại cho người dùng. Các bộ gõ phổ biến hiện nay trên Windows theo mình biết đều do cá nhân phát triển nhưng không hề bị tình trạng đem con bỏ chợ như bên Linux.
Từ góc độ kĩ thuật và định hướng phát triển thì việc gộp 2 bộ gõ không những không khả thi mà còn khiến dự án chết nhanh hơn, cụ thể:
- Engine xử lý tiếng Việt của 2 bộ gõ được phát triển hoàn toàn độc lập với nhau, nếu muốn gộp phải gộp 2 engine này lại trước mà mình thì không biết phải bắt đầu từ đâu trước cả.
- Teni phụ thuộc rất lớn vào từ điển, mình nghĩ đây là điều rất xấu vì từ điển của teni chỉ có khoảng 8.000 từ đơn trong khi số từ tiếng Việt có thể phát âm được lên đến 20.504 từ. Hệ quả là rất nhiều từ lóng, từ địa phương, tên riêng không thể gõ được bằng teni theo cách thông thường. VD: giũng, rũng, đệu, rềnh, pặp, khuống, hoóng, đuống, vừ, sếnh, hụy, khụy, chụy,... Quan trọng hơn, tiếng Việt không phải một ngôn ngữ chết mà liên tục thay đổi, tiến hóa. Không ai có thể đủ sức, đủ chuyên môn để chạy theo cập nhật, sửa đổi, bổ sung mãi mãi được.
- Hiện nay vẫn còn khá nhiều tài liệu, phông chữ sử dụng bảng mã cũ (TCVN, VNI, ...) đang được lưu hành và sử dụng. Sẽ rất đáng tiếc nếu không thể sử dụng chúng trên Linux như trên các hệ điều hành khác (dù sao cũng là công sức của rất nhiều người đi trước không phải muốn bỏ là bỏ được). Vì vậy mình sẽ cố gắng duy trì các bảng mã, kiểu gõ cũ hết mức có thể.

**Comment by openhoangnc** [comment]
Mình phản biện ý thứ 2 của @luongthanhlam Tắt "Đúng chính tả" sẽ cho phép gõ thứ gì cũng được.
VD: giũng, rũng, đệu, rềnh, pặp, khuống, hoóng, đuống, vừ, sếnh, hụy, khụy, chụy, sỉu, tỉu, tìu, hỉu,... đều gõ được
Số tiếng có thể phát âm sẽ nhiều hơn số tiếng thực dùng trong tiếng Việt là điều hiển nhiên, từ người Việt có dùng thì có trong từ điển. Lý luận về sự phát triển của tiếng Việt của bạn là quá xa với tiêu chí bộ gõ của mình.

**Comment by luongthanhlam** [comment]
Với người dùng Telex, chức năng Kiểm tra chính tả (trong teni gọi là Đúng chính tả) ngoài mục đích phát hiện từ tiếng Việt gõ sai chính tả thì còn có tác dụng gõ nhanh từ chuyên ngành, từ tiếng Anh nên nếu không phải trong trường hợp bất đắc dĩ không ai muốn tắt kiểm tra chính tả cả. Như mình dùng unikey nhiều năm rồi nhưng gần như không bao giờ phải vào cài đặt cấu hình gì cả.

Ngoài ra, mình không rõ bạn định nghĩa Đúng chính tả là gì nhưng trên wikipedia mình đọc người ta định nghĩa thế này:
Trong ngôn ngữ học, chính tả của một ngôn ngữ là **một hệ thống các quy tắc ghi chép lại lời nói được cộng đồng người sử dụng chấp nhận một cách chính thức hoặc rộng rãi**. "Chính tả" là một từ Hán Việt, trong đó "chính" 正 có nghĩa là đúng, "tả" 寫 có nghĩa là viết, "chính tả" 正寫 dịch sát nghĩa từng chữ là "viết đúng".
https://vi.wikipedia.org/wiki/Ch%C3%ADnh_t%E1%BA%A3
Như vậy, theo mình thì những từ trên đều là từ đúng chính tả, chỉ khi người dùng dùng sai mới thành sai chính tả.

**Comment by openhoangnc** [comment]
@luongthanhlam không có tính xây dựng, bình luận nhằm mục đích công kích, mình sẽ không phí thời gian nữa.
Mình vẫn bảo lưu ý kiến của mình về cậu này:
**Toàn bộ project ibus-bamboo được re-upload, rename từ ibus-teni, sau khi mình có ý kiến mới cập nhật nguồn fork**
