### ISSUE TITLE
Gõ kiểu Teni trên sublime text 3 được không ?

### ISSUE THREAD

**Issue by HaiHoangCong** [teni-ime/ibus-teni#82]
Cho mình hỏi iBus-Teni của bạn có gõ được kiểu Teni trên sublime text 3 không vậy ? 
Nếu gõ được thì cái đặt như thế nào vậy ? mình trước cài vn ime nên bây giờ chỉ gõ được telex.

**Môi trường**
 - OS và version: Ubuntu 18.04 LTS
 - Desktop: Default
 - Phiên bản ibus-teni: v1.5.2
 - Phiên bản IBus: IBus 1.5.17
 - Ứng dụng có lỗi khi gõ: Sublime text 3

**Comment by khanhicetea** [comment]
Theo mình biết thì ibus không support cho Sublime Text trên linux nhé, bạn có thể dùng một số plugin của ST 3 để gõ hoặc chuyển đổi qua một số Editor nền Electron khác như VSCode (khuyên dùng) hoặc Atom nhé

**Comment by Thevan96** [comment]
Có 2 plugin gõ tiếng việt trong sublime text là vn-me và bogo. Theo như
mình từng sử dụng thì bogo nó sử dụng tốt hơn so với vn-me, vn-me nhiều lúc
si đa vl ra, nhất là làm web chuyển đổi qua về en vn với lại gõ ko sướng.
Bạn thử cả 2 xem cái nào phù hợp để sử dụng

Vào 15:41 T.5, 27 Th12 2018 KhanhIceTea <notifications@github.com đã viết:

**Comment by Thevan96** [comment]
https://github.com/pirackr/Sublime-Bogo
https://github.com/glmanhtu/VN_IME


Vào 15:53 T.5, 27 Th12 2018 Thế Văn Võ <vothevan96@gmail.com đã viết:

**Comment by ghinlop** [comment]
Bạn mình hiện xài linux mint 19 và đang dùng teni trên sublime text và thấy gõ tiếng việt bình thường. Chỉ có hay bị hiện tượng mất chữ.

**Comment by openhoangnc** [comment]
@khanhicetea @Thevan96 @ghinlop Cảm ơn các bạn đã trả lời.

@HaiHoangCong mình kiểm tra thì ibus không hoạt động với Sublime Text trên Ubuntu, kéo theo tất cả bộ gõ dựa trên ibus (ibus-unikey, ibus-bogo, ibus-teni,...) đều không gõ được trên Sublime Text.

Còn về kiểu gõ thì ibus-teni cho phép gõ cả Telex và Vni.

Bạn có thể xem xét các giải pháp dùng Editor khác thay thế (mình cũng khuyên dùng VSCode, hơi chậm hơn so với Sublime Text nhưng Extension cực kì phong phú).

Mình close issues, nếu có thông tin gì mới thì mọi người đều có thể comment thêm.
