### ISSUE TITLE
Lỗi không gõ được tiếng việt trên Ubuntu 18.04

### ISSUE THREAD

**Issue by Hieunv1996** [teni-ime/ibus-teni#83]
**Mô tả lỗi**
Gõ ok trên Chrome, nhưng lại không thể gõ Tiếng Việt trên các PM khác: Sublime Text, Skype, 
**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: Mặc định
 - Phiên bản ibus-teni: 1.5.2
 - Phiên bản IBus: 1.5.17
 - Ứng dụng có lỗi khi gõ: Sublime Text, Skype
**Mô tả thêm**
- Mình cài ibus-unikey cũng bị y như vậy.

**Comment by khanhicetea** [comment]
- Không biết có phải bạn cài Skype qa snap không ?
- Sublime Text thì xưa giờ ko support ibus nên bạn có thể dùng plugin input-helper hoặc switch qua Editor khác như VSCode hoặc Atom.

**Comment by Hieunv1996** [comment]
Vậy đúng như anh nói rồi ạ. Em cảm ơn anh

**Comment by khanhicetea** [comment]
Nếu đã giải quyết được issus thì bạn Close lại nhé :)

**Comment by trmaphi** [comment]
@khanhicetea Nếu cài Skype qua snap thì sẽ không dùng được ibus hả, bạn?

**Comment by ghinlop** [comment]
@trmaphi hiện tại thì các app cài từ snap thì dùng ibus gõ tiếng việt ko được nhà bạn. Bạn có thể cài Skype từ deb đc mà.

**Comment by trmaphi** [comment]
@ghinlop hình như Skype build trong snap không support ibus. Mình dùng [caprine](https://github.com/sindresorhus/caprine) cũng trong bằng snap nhưng vẫn dùng ibus bình thường.

**Comment by khanhicetea** [comment]
Đa phần apps cài qua snaps sẽ không support ibus, còn trường hợp **caprine** của bạn chắc do app đó thật ra là web apps được build trên nền ElectronJS
