### ISSUE TITLE
Lỗi nhập một ký tự hiển thị hai ký tự đối với những chữ như c, p...

### ISSUE THREAD

**Issue by huynhduckhoan** [teni-ime/ibus-teni#9]
Như tiêu đề khi mình gõ trên thanh địa chỉ trình duyệt thì nó sẽ bị lặp từ đối với các chữ như c, p... 
Ví dụ như mình gõ chữ c thì nó hiển thị ra cc.

- Hệ điều hành: Elementary.
- Trình duyệt: Yandex Browser

**Comment by openhoangnc** [comment]
@huynhduckhoan cảm ơn bạn đã tạo issue, mình sẽ kiểm tra và tìm cách khắc phục

**Comment by huynhduckhoan** [comment]
Đã không còn lỗi nữa... Sửa ở phiên bản nào thì mình không biết... Cảm ơn mấy bác...
